### ISSUE TITLE
This optimization is very good, thank you very much, can you upgrade it to be compatible with magento2.4.5

### ISSUE THREAD

**Issue by writyou** [jq91/magento2-luma-optimized#2]
This optimization is very good, thank you very much, can you upgrade it to be compatible with magento2.4.5

**Comment by writyou** [comment]
hi

**Comment by dev-jq** [comment]
Hi, @writyou 

If you have no idea or knowledge how to implement compatible with Magento 2.4.5 and you are still interested in it - [write a private message to me](mailto:jan.pason@gmail.com). 

Regards

**Comment by cptX** [comment]
So, with which versions is it compatible? It's not compatible with 2.4.5? Can you explain briefly what needs to get modified in order to work with 2.4.5?

**Comment by dev-jq** [comment]
Hi @cptX,
this was developed for Magento version 2.3.x. Since version 2.4.x there have been a lot of changes, e.g. in the paths of jquery widgets. So now there is a problem with reqiureJS and accessing the correct file paths.

**Right now I'm working on releasing a luma based template that will include the full Core Web Vitals and SEO optimization package as well as many new features that the basic Luma skin doesn't have. This will be a premium paid solution.**

**Comment by writyou** [comment]
> 

This is really good news

**Comment by dev-jq** [comment]
**Breaking news!**
If you are interested, please refer to my new repo:
 :point_right: [github.com/jq91/M2-AzkarraTheme-for-Core-Web-Vitals-and-SEO](https://github.com/jq91/M2-AzkarraTheme-for-Core-Web-Vitals-and-SEO)

**Comment by dev-jq** [comment]
Dear @writyou, @cptX

I am thrilled to share some fantastic news with all of you who have been following my project. The Azkara Theme on Magento 2.4.5, complete with demo data, is now available!

👉 [CLICK HERE to see AZKARRA in action](https://m10393.app-on-demand.net/) 👈

[More info here](https://jqdev.gumroad.com/l/azkarra-theme)
